"""Command-line interface for the RBC pipeline.

Entry point that parses arguments, validates BIDS inputs, and dispatches to
the appropriate workflow. Each subcommand (``anatomical``, ``functional``,
``derivatives``, ``longitudinal``, ``qc``) is defined in its own submodule
under ``rbc.cli``.
"""

from __future__ import annotations

from rbc.core import CPAC_ANTS_SEED

_DEFAULT_ENV_VARS = {
    "ITK_GLOBAL_DEFAULT_NUMBER_OF_THREADS": "1",
    "ANTS_RANDOM_SEED": CPAC_ANTS_SEED,
}

_SUB_SES_QUERY = ("sub", "ses")

_ANAT_GROUP_ENTITIES = ("run", "acq", "suffix", "part", "echo", "ce", "rec", "inv")
"""BIDS entities used to group anatomical files in dataframes generated by Bids2Table;
includes ``suffix`` to distinguish T1w, T2w, etc."""

_FUNC_GROUP_ENTITIES = ("task", "run", "acq", "dir", "echo", "part", "rec")
"""BIDS entities used to group functional files in dataframes generated by Bids2Table;
exclude ``suffix` so 'sbref' stays grouped with 'bold'."""
