"""Full pipeline test for longitudinal QC.

Verifies that ``rbc longitudinal qc`` produces a registration-quality
TSV with Dice/Jaccard metrics and a pass/fail flag.
"""

from __future__ import annotations

import base64
import csv
import re
from typing import TYPE_CHECKING

import pytest

if TYPE_CHECKING:
    from pathlib import Path


_SUB = "01"
_SES = "test"
_TASK = "fingerfootlips"
_STEM = f"sub-{_SUB}_ses-{_SES}_task-{_TASK}"
_SVG_RE = re.compile(r'src="data:image/svg\+xml;base64,([A-Za-z0-9+/=]+)"')


def _file_tree(root: Path) -> str:
    files = sorted(p.relative_to(root) for p in root.rglob("*") if p.is_file())
    return "\n".join(str(f) for f in files) if files else "(empty)"


@pytest.mark.slow
def test_longitudinal_qc_tsv_exists(
    longitudinal_pipeline_data: Path,
) -> None:
    """QC stage writes a registration quality TSV."""
    func = longitudinal_pipeline_data / f"sub-{_SUB}" / f"ses-{_SES}" / "func"
    tree = _file_tree(longitudinal_pipeline_data)

    qc_files = list(func.glob(f"{_STEM}_space-longitudinal_*quality*.tsv"))
    assert qc_files, f"No QC quality TSV found\n--- file tree ---\n{tree}"


@pytest.mark.slow
def test_longitudinal_qc_tsv_has_expected_columns(
    longitudinal_pipeline_data: Path,
) -> None:
    """QC TSV contains dice, jaccard, coverage, cross_corr, passed columns."""
    func = longitudinal_pipeline_data / f"sub-{_SUB}" / f"ses-{_SES}" / "func"
    qc_files = list(func.glob(f"{_STEM}_space-longitudinal_*quality*.tsv"))
    assert qc_files, "No QC quality TSV found"

    with qc_files[0].open() as fh:
        reader = csv.DictReader(fh, delimiter="\t")
        rows = list(reader)

    assert len(rows) == 1, f"Expected 1 row, got {len(rows)}"
    expected_cols = {
        "sub",
        "ses",
        "task",
        "run",
        "dice",
        "jaccard",
        "coverage",
        "cross_corr",
        "passed",
    }
    assert expected_cols.issubset(rows[0].keys()), (
        f"Missing columns: {expected_cols - rows[0].keys()}"
    )

    # Dice should be a reasonable value (> 0 at minimum)
    dice = float(rows[0]["dice"])
    assert dice > 0.0, f"Dice coefficient is {dice}, expected > 0"


# ---------------------------------------------------------------------------
# Per-subject HTML QC report (issue #304)
# ---------------------------------------------------------------------------


def _report_path(root: Path) -> Path:
    """Return the per-subject QC HTML report, asserting it exists."""
    func = root / f"sub-{_SUB}" / "ses-longitudinal" / "func"
    reports = list(func.glob(f"sub-{_SUB}_ses-longitudinal_space-longitudinal_QC.html"))
    assert reports, (
        f"No per-subject QC HTML report found\n--- file tree ---\n{_file_tree(root)}"
    )
    return reports[0]


@pytest.mark.slow
def test_qc_report_exists(longitudinal_pipeline_data: Path) -> None:
    """``longitudinal qc`` writes a per-subject HTML QC report."""
    _report_path(longitudinal_pipeline_data)


@pytest.mark.slow
def test_qc_report_has_all_sections(longitudinal_pipeline_data: Path) -> None:
    """The report contains summary, registration, coverage, and motion."""
    html = _report_path(longitudinal_pipeline_data).read_text(encoding="utf-8")
    for needle in (
        "Registration QC Summary",
        "Registration: sessions on the longitudinal template",
        "Coverage: BOLD across sessions",
        "Motion by session",
        "Generated by RBC",
    ):
        assert needle in html, f"Missing section: {needle!r}"


@pytest.mark.slow
def test_qc_report_covers_both_sessions(longitudinal_pipeline_data: Path) -> None:
    """Both sessions are summarized in the per-subject report."""
    html = _report_path(longitudinal_pipeline_data).read_text(encoding="utf-8")
    assert "ses-test" in html
    assert "ses-retest" in html


@pytest.mark.slow
def test_qc_report_svg_valid_and_self_contained(
    longitudinal_pipeline_data: Path,
) -> None:
    """Embedded figures are valid SVG data URIs with no external URLs."""
    html = _report_path(longitudinal_pipeline_data).read_text(encoding="utf-8")
    svgs = _SVG_RE.findall(html)
    assert svgs, "No embedded SVG figures found"
    for b64 in svgs:
        assert base64.b64decode(b64).startswith(b"<?xml"), "SVG did not decode"
    assert "http://" not in html
    assert "https://" not in html
