"""Unit tests for rbc.core.longitudinal.report."""

from __future__ import annotations

import base64
import re
from dataclasses import replace
from typing import TYPE_CHECKING

import matplotlib.pyplot as plt
import nibabel as nib
import numpy as np
import pytest

from rbc.core.longitudinal.report import (
    ReportSection,
    _to_grid,
    generate_qc_report,
    render_motion_by_session,
)
from rbc.core.qc.registration import RegistrationQCMetrics

if TYPE_CHECKING:
    from pathlib import Path

_SHAPE3 = (16, 16, 16)
_N_VOLS = 20
_SVG_RE = re.compile(r'src="data:image/svg\+xml;base64,([A-Za-z0-9+/=]+)"')
_SVG_PREFIX = b"<?xml"


def _write_nifti(
    path: Path,
    data: np.ndarray,
    spacing: float = 2.0,
) -> Path:
    """Write *data* to *path* as a float32 NIfTI with diagonal spacing."""
    affine = np.diag([spacing, spacing, spacing, 1.0])
    nib.Nifti1Image(data.astype(np.float32), affine).to_filename(str(path))
    return path


def _sphere(shape: tuple[int, int, int]) -> np.ndarray:
    """Return a spherical mask on a grid of *shape*."""
    cx, cy, cz = (s / 2 for s in shape)
    xx, yy, zz = np.mgrid[0 : shape[0], 0 : shape[1], 0 : shape[2]]
    d2 = (xx - cx) ** 2 + (yy - cy) ** 2 + (zz - cz) ** 2
    return (d2 < (min(shape) / 2) ** 2).astype(np.float32)


def _metrics(dice: float = 0.9) -> RegistrationQCMetrics:
    """Build a passing-quality registration metrics row."""
    return RegistrationQCMetrics(dice=dice, jaccard=0.8, cross_corr=0.88, coverage=0.95)


def _section(
    tmp_path: Path,
    ses: str,
    *,
    rng: np.random.Generator,
    dice: float = 0.9,
) -> ReportSection:
    """Build one synthetic session (template, masks, motion) under *tmp_path*."""
    d = tmp_path / f"ses-{ses}"
    d.mkdir(parents=True, exist_ok=True)
    template = _write_nifti(d / "template.nii.gz", rng.random(_SHAPE3) * 100)
    # BOLD mask on a different grid: exercises the _to_grid resample branch.
    bold = _write_nifti(d / "bold_mask.nii.gz", _sphere((12, 12, 12)), spacing=2.5)
    anat = _write_nifti(d / "anat_mask.nii.gz", _sphere(_SHAPE3))
    rms_rel = d / "rel.rms"
    np.savetxt(rms_rel, rng.random(_N_VOLS - 1) * 0.1)
    return ReportSection(
        ses=ses,
        run=0,
        metrics=_metrics(dice),
        passed=True,
        anat_mask=anat,
        bold_mask=bold,
        template=template,
        rms_rel=rms_rel,
    )


@pytest.fixture
def sessions(tmp_path: Path) -> list[ReportSection]:
    """Two synthetic sessions (ses-test, ses-retest)."""
    rng = np.random.default_rng(7)
    return [_section(tmp_path, ses, rng=rng) for ses in ("test", "retest")]


class TestGenerateQcReport:
    """End-to-end generation on synthetic sessions."""

    def test_report_written_and_complete(
        self, sessions: list[ReportSection], tmp_path: Path
    ) -> None:
        """A full report is written with all sections, SVGs, and no URLs."""
        out = (
            tmp_path / "deriv" / "sub-01" / "func" / "sub-01_space-longitudinal_QC.html"
        )
        result = generate_qc_report(sub="01", sessions=sessions, out_path=out)
        assert result == out
        assert out.is_file()

        html = out.read_text(encoding="utf-8")
        for needle in (
            "Registration QC Summary",
            "Registration: sessions on the longitudinal template",
            "Coverage: BOLD across sessions",
            "Motion by session",
            "QC PASSED",
            "Dice &ge; 0.85",
            "0.900",
            "0.800",
            "0.880",
            "0.950",
            "ses-test",
            "ses-retest",
            "Generated by RBC",
        ):
            assert needle in html, needle

        # Two registration + one coverage + one motion figure.
        svgs = _SVG_RE.findall(html)
        assert len(svgs) == 4
        for b64 in svgs:
            assert base64.b64decode(b64).startswith(_SVG_PREFIX)

        assert "http://" not in html
        assert "https://" not in html
        assert [p.name for p in out.parent.iterdir()] == [out.name]

    def test_failed_banner_when_any_session_fails(
        self, sessions: list[ReportSection], tmp_path: Path
    ) -> None:
        """One failed run flips the banner to QC FAILED."""
        sessions[0] = replace(sessions[0], passed=False, metrics=_metrics(dice=0.5))
        out = generate_qc_report(
            sub="01", sessions=sessions, out_path=tmp_path / "qc.html"
        )
        html = out.read_text(encoding="utf-8")
        assert "QC FAILED" in html
        assert "QC PASSED" not in html
        assert "FAIL" in html

    def test_single_session_renders_three_figures(
        self, sessions: list[ReportSection], tmp_path: Path
    ) -> None:
        """A single session yields one registration, coverage, and motion SVG."""
        out = generate_qc_report(
            sub="01", sessions=sessions[:1], out_path=tmp_path / "qc.html"
        )
        html = out.read_text(encoding="utf-8")
        assert len(_SVG_RE.findall(html)) == 3
        assert "QC PASSED" in html

    def test_subject_label_is_escaped(
        self, sessions: list[ReportSection], tmp_path: Path
    ) -> None:
        """HTML special characters in the subject ID are escaped."""
        out = generate_qc_report(
            sub="01<>", sessions=sessions, out_path=tmp_path / "qc.html"
        )
        html = out.read_text(encoding="utf-8")
        assert "sub-01&lt;&gt;" in html
        assert "sub-01<>" not in html

    def test_run_labels_disambiguate_repeated_sessions(
        self, sessions: list[ReportSection], tmp_path: Path
    ) -> None:
        """Two runs of the same session get distinct labels."""
        sec2 = replace(sessions[0], run=2)
        out = generate_qc_report(
            sub="01",
            sessions=[sessions[0], sec2],
            out_path=tmp_path / "qc.html",
        )
        html = out.read_text(encoding="utf-8")
        assert "ses-test_run2" in html


class TestToGrid:
    """Shape-guarded resampling helper."""

    def test_same_grid_returns_same_image(self, tmp_path: Path) -> None:
        """A mask already on the reference grid is returned untouched."""
        ref = nib.nifti1.load(_write_nifti(tmp_path / "ref.nii.gz", np.ones(_SHAPE3)))
        assert _to_grid(ref, ref) is ref

    def test_different_grid_is_resampled(self, tmp_path: Path) -> None:
        """A mask on a different grid is resampled onto the reference grid."""
        ref = nib.nifti1.load(_write_nifti(tmp_path / "ref.nii.gz", np.ones(_SHAPE3)))
        img = nib.nifti1.load(
            _write_nifti(tmp_path / "img.nii.gz", np.ones((12, 12, 12)), spacing=2.5)
        )
        out = _to_grid(img, ref)
        assert out.shape[:3] == _SHAPE3


class TestRenderMotionBySession:
    """Per-session FD trace renderer."""

    def test_one_line_per_session_plus_threshold(self) -> None:
        """Each session gets one trace plus the shared threshold line."""
        fig = plt.figure()
        ax = fig.add_subplot(1, 1, 1)
        fd_a = np.linspace(0.0, 0.3, _N_VOLS)
        fd_b = np.linspace(0.1, 0.5, _N_VOLS)
        render_motion_by_session(
            ax, fd_by_session={"ses-test": fd_a, "ses-retest": fd_b}
        )
        # Two traces + the shared threshold line.
        assert len(ax.get_lines()) == 3
        _, labels = ax.get_legend_handles_labels()
        assert labels == ["ses-test", "ses-retest"]
        plt.close(fig)
