# Auto-generated by scripts/generate_bids_tools.py — DO NOT EDIT
# Regenerate with: uv run scripts/generate_bids_tools.py
"""Unit tests for rbc.core.bids (auto-generated)."""

from pathlib import PurePath

import pytest

from rbc.core.bids import (
    BIDSFile,
    Datatype,
    Modality,
    Suffix,
    bids_name,
    bids_path,
    parse_bids_name,
)


@pytest.mark.unit
class TestBidsName:
    """Tests for bids_name."""

    def test_basic(self) -> None:
        """Build a simple filename with sub + suffix."""
        result = bids_name(sub="01", suffix="T1w", extension=".nii.gz")
        assert result == "sub-01_T1w.nii.gz"

    def test_multiple_entities(self) -> None:
        """Build filename with several entities."""
        result = bids_name(
            sub="01",
            ses="pre",
            task="rest",
            run=2,
            desc="preproc",
            suffix="bold",
            extension=".nii.gz",
        )
        assert result == ("sub-01_ses-pre_task-rest_run-2_desc-preproc_bold.nii.gz")

    def test_entity_ordering(self) -> None:
        """Entities are ordered per the BIDS spec regardless of kwarg order."""
        result = bids_name(
            desc="x",
            run=1,
            ses="A",
            sub="01",
            suffix="T1w",
            extension=".nii.gz",
        )
        assert result.startswith("sub-01_ses-A_")
        assert result.endswith("_desc-x_T1w.nii.gz")

    def test_index_entity(self) -> None:
        """Index entities accept int and format without zero-padding."""
        result = bids_name(sub="01", run=3, suffix="bold", extension=".nii.gz")
        assert "run-3" in result

    def test_suffix_only(self) -> None:
        """When no entities are given, result is just suffix + ext."""
        result = bids_name(suffix="participants", extension=".tsv")
        assert result == "participants.tsv"

    def test_invalid_label_raises(self) -> None:
        """Labels with invalid characters raise ValueError."""
        with pytest.raises(ValueError, match="Invalid label"):
            bids_name(
                sub="bad label!",
                suffix="T1w",
                extension=".nii.gz",
            )

    def test_negative_index_raises(self) -> None:
        """Negative index values raise ValueError."""
        with pytest.raises(ValueError, match="Negative index"):
            bids_name(
                sub="01",
                run=-1,
                suffix="T1w",
                extension=".nii.gz",
            )

    def test_enum_entity(self) -> None:
        """Enum entity 'mt' accepts allowed values."""
        result = bids_name(
            sub="01",
            mt="on",
            suffix="T1w",
            extension=".nii.gz",
        )
        assert "mt-on" in result

    def test_with_suffix_constant(self) -> None:
        """Suffix constants work as suffix values."""
        result = bids_name(sub="01", suffix=Suffix.T1W, extension=".nii.gz")
        assert result == "sub-01_T1w.nii.gz"


@pytest.mark.unit
class TestBidsPath:
    """Tests for bids_path."""

    def test_with_datatype(self) -> None:
        """Path includes sub/ses/datatype directories."""
        result = bids_path(
            sub="01",
            ses="pre",
            suffix="T1w",
            extension=".nii.gz",
            datatype=Datatype.ANAT,
        )
        expected = PurePath(
            "sub-01",
            "ses-pre",
            "anat",
            "sub-01_ses-pre_T1w.nii.gz",
        )
        assert result == expected

    def test_sub_only(self) -> None:
        """Path with subject but no session."""
        result = bids_path(
            sub="01",
            suffix="T1w",
            extension=".nii.gz",
            datatype=Datatype.ANAT,
        )
        expected = PurePath("sub-01", "anat", "sub-01_T1w.nii.gz")
        assert result == expected

    def test_no_datatype(self) -> None:
        """Path without datatype only has sub/ses dirs."""
        result = bids_path(
            sub="01",
            ses="01",
            suffix="scans",
            extension=".tsv",
        )
        expected = PurePath("sub-01", "ses-01", "sub-01_ses-01_scans.tsv")
        assert result == expected

    def test_returns_purepath(self) -> None:
        """Return type is PurePath."""
        result = bids_path(
            sub="01",
            suffix="T1w",
            extension=".nii.gz",
        )
        assert isinstance(result, PurePath)


@pytest.mark.unit
class TestParseBidsName:
    """Tests for parse_bids_name."""

    def test_basic_parse(self) -> None:
        """Parse a standard BIDS filename."""
        result = parse_bids_name("sub-01_ses-pre_desc-brain_T1w.nii.gz")
        assert result == BIDSFile(
            entities={"sub": "01", "ses": "pre", "desc": "brain"},
            suffix="T1w",
            extension=".nii.gz",
        )

    def test_compound_extension(self) -> None:
        """Compound extensions like .nii.gz are kept intact."""
        result = parse_bids_name("sub-01_bold.nii.gz")
        assert result.extension == ".nii.gz"
        assert result.suffix == "bold"

    def test_simple_extension(self) -> None:
        """Simple extensions are parsed correctly."""
        result = parse_bids_name("sub-01_ses-01_scans.tsv")
        assert result.extension == ".tsv"
        assert result.suffix == "scans"

    def test_no_extension(self) -> None:
        """Filenames without extensions are handled."""
        result = parse_bids_name("sub-01_T1w")
        assert result.extension == ""
        assert result.suffix == "T1w"

    def test_index_entity_as_string(self) -> None:
        """Parsed index entities are returned as strings."""
        result = parse_bids_name("sub-01_run-2_bold.nii.gz")
        assert result.entities["run"] == "2"

    def test_round_trip(self) -> None:
        """Build then parse produces matching components."""
        name = bids_name(
            sub="01",
            ses="pre",
            run=3,
            desc="preproc",
            suffix="bold",
            extension=".nii.gz",
        )
        parsed = parse_bids_name(name)
        assert parsed.suffix == "bold"
        assert parsed.extension == ".nii.gz"
        assert parsed.entities["sub"] == "01"
        assert parsed.entities["ses"] == "pre"
        assert parsed.entities["run"] == "3"
        assert parsed.entities["desc"] == "preproc"


@pytest.mark.unit
class TestConstants:
    """Tests for namespace constant classes."""

    def test_datatype_values(self) -> None:
        """Datatype constants hold the expected string values."""
        assert Datatype.ANAT == "anat"
        assert Datatype.BEH == "beh"
        assert Datatype.DWI == "dwi"
        assert Datatype.EEG == "eeg"
        assert Datatype.EMG == "emg"

    def test_suffix_values(self) -> None:
        """Suffix constants hold the expected string values."""
        assert Suffix.T1W == "T1w"
        assert Suffix.T2W == "T2w"
        assert Suffix.BOLD == "bold"
        assert Suffix.DWI == "dwi"
        assert Suffix.EVENTS == "events"
        assert Suffix.MASK == "mask"

    def test_modality_values(self) -> None:
        """Modality constants hold the expected string values."""
        assert Modality.BEH == "beh"
        assert Modality.EEG == "eeg"
        assert Modality.EMG == "emg"
        assert Modality.IEEG == "ieeg"
