name: Full Testing Suite

permissions:
  contents: write

on:
  workflow_dispatch:
    inputs:
      cleanup:
        description: Clean up job folder after running tests
        default: true
        type: boolean

jobs:
  test:
    runs-on: arcana
    steps:
    - uses: actions/checkout@v6
    - name: Setup venv
      uses: ./.github/actions/setup-venv

    - name: Run all tests
      shell: bash
      run: |
        export JOB_TMP="/tmp/rbc_test_$(date +%s%N)"
        mkdir -p $JOB_TMP
        echo "JOB_TMP=$JOB_TMP" >> $GITHUB_ENV
        echo "Job temp directory: $JOB_TMP"

        export PYTEST_CACHE_DIR="$JOB_TMP/.pytest_cache"
        export PYTHONPYCACHEPREFIX="$JOB_TMP/__pycache__"
        export COVERAGE_FILE="$JOB_TMP/.coverage"

        uv run pytest \
          -n auto \
          --runner=podman \
          --basetemp=$JOB_TMP/pytest-tmp \
          --cov-report= \
          --cov=src tests \
          --verbose

    - name: Coverage summary
      if: always()
      env:
        COVERAGE_FAIL: 75
      shell: bash
      run: |
        uv run coverage report \
          --data-file=$JOB_TMP/.coverage \
          --fail-under=$COVERAGE_FAIL \
          --show-missing \
          --format=markdown >> $GITHUB_STEP_SUMMARY

    - name: Cleanup
      if: ${{ always() && github.event.inputs.cleanup == 'true' }}
      shell: bash
      run: |
        echo "Cleaning up job temp directory: $JOB_TMP"
        rm -rf $JOB_TMP
